### ISSUE TITLE
Content-range header

### ISSUE THREAD

**Issue by ytzlax** [mscdex/httpolyglot#15]
Hi,

Just want to ask, do you support content-range header?

thanks

**Comment by mscdex** [comment]
This module does nothing with the http requests or responses. You'll get them as-is.

**Comment by ytzlax** [comment]
I see in the readme example, that you can write
```
 res.writeHead(200, { 'Content-Type': 'text/plain' });
```
So my question is, can I write
```
 res.writeHead(206, { 'Content-range': 'bytes 200-1000/67589 });
```
?

**Comment by mscdex** [comment]
It's just an example, you can respond however you like. It's irrelevant to `httpolyglot`.
