### ISSUE TITLE
Node v0.12 compatibility

### ISSUE THREAD

**Issue by andrewrk** [mscdex/httpolyglot#2]
Upgrading to node v0.12 causes websockets to break.

I love this module; I hope it can work in Node v0.12.

**Comment by mscdex** [comment]
I'm not sure what you mean, the readme examples work for me on node v0.12 and latest iojs.

Do you have a simple, minimal test case that reproduces the problem?

**Comment by andrewrk** [comment]
How's this?

https://gist.github.com/andrewrk/5ead7be91519d704688b

**Comment by mscdex** [comment]
Can you try the master branch now and let me know if it's working for you?

**Comment by andrewrk** [comment]
Wonderful. Fixed :)

**Comment by mscdex** [comment]
Published in v0.1.1.
