### ISSUE TITLE
nmap probe brings the server down

### ISSUE THREAD

**Issue by tkurki** [mscdex/httpolyglot#5]
The example app in the readme crashes with 

```
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1026:11)
    at TCP.onread (net.js:564:26)
```

when touched with `nmap localhost -p9000`. 

I assume nmap disconnects right after connect and the connection gets reset.

**Comment by mscdex** [comment]
Does it send data at all or ? Did you try this with just a plain http or plain https server?

**Comment by tkurki** [comment]
Don't know, my guess is that nmap just knocks on the port and when somebody answers hangs up.
