### ISSUE TITLE
express example?

### ISSUE THREAD

**Issue by coderofsalvation** [mscdex/httpolyglot#8]
```
var app = express()
app.listen(80)
```

This is how express apps work.
Any idea where the `createServer()` comes in to the picture?
Would love to get this working for express..

**Comment by mscdex** [comment]
Just use it like you would [with `http.createServer()`/`https.createServer()`](http://expressjs.com/en/4x/api.html#app.listen). For example:

```js
var app = express();

// ...

httpolyglot.createServer({ /*...*/ }, app).listen(/*...*/);
```

**Comment by coderofsalvation** [comment]
thanks !

**Comment by JamesStark-wasp** [comment]
Thanks
